---
# Include variables and define needed ones
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Define Python packages
  ansible.builtin.set_fact:
    netbox_python_packages: "{{ __netbox_python_packages | list }}"
  when: netbox_python_packages is not defined

- name: Define PostgreSQL packages
  ansible.builtin.set_fact:
    netbox_postgresql_packages: "{{ __netbox_postgresql_packages | list }}"
  when: netbox_postgresql_packages is not defined

- name: Define Redis packages
  ansible.builtin.set_fact:
    netbox_redis_packages: "{{ __netbox_redis_packages | list }}"
  when: netbox_redis_packages is not defined

- name: Define LDAP packages
  ansible.builtin.set_fact:
    netbox_ldap_packages: "{{ __netbox_ldap_packages | list }}"
  when: netbox_ldap_packages is not defined

- name: Define other packages
  ansible.builtin.set_fact:
    netbox_other_packages: "{{ __netbox_other_packages | list }}"
  when: netbox_other_packages is not defined

- name: Define web frontend packages
  ansible.builtin.set_fact:
    netbox_web_frontend_packages: "{{ __netbox_web_frontend_packages | list }}"
  when: netbox_web_frontend_packages is not defined
