---
- name: Ensure PostgreSQL is ready
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Create PostgreSQL database
  community.postgresql.postgresql_db:
    name: "{{ netbox_database }}"
  become: true
  become_user: "{{ netbox_postgresql_user }}"

- name: Create PostgreSQL user
  community.postgresql.postgresql_user:
    name: "{{ netbox_database_user }}"
    password: "{{ netbox_database_password }}"
    encrypted: true
    db: "{{ netbox_database }}"
  become: true
  become_user: "{{ netbox_postgresql_user }}"

- name: Grant ALL privileges to PostgreSQL user
  community.postgresql.postgresql_privs:
    db: "{{ netbox_database }}"
    privs: ALL
    role: "{{ netbox_database_user }}"
    type: database
  become: true
  become_user: "{{ netbox_postgresql_user }}"

- name: Ensure Redis is ready
  ansible.builtin.service:
    name: "{{ netbox_redis_service }}"
    state: started
