---
- name: Ensure PostgreSQL is ready
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Create PostgreSQL database
  community.postgresql.postgresql_db:
    name: "{{ netbox_database }}"
  become: true
  become_user: "{{ netbox_postgresql_user }}"

- name: Create PostgreSQL user
  community.postgresql.postgresql_user:
    name: "{{ netbox_database_user }}"
    password: "{{ netbox_database_password }}"
    encrypted: true
    login_db: "{{ netbox_database }}"
  become: true
  become_user: "{{ netbox_postgresql_user }}"

- name: Set PostgreSQL user as owner of database
  community.postgresql.postgresql_owner:
    login_db: "{{ netbox_database }}"
    new_owner: "{{ netbox_database_user }}"
  become: true
  become_user: "{{ netbox_postgresql_user }}"

- name: Grant ALL privileges to PostgreSQL user
  community.postgresql.postgresql_privs:
    login_db: "{{ netbox_database }}"
    privs: ALL
    type: schema
    objs: public
    role: "{{ netbox_database_user }}"
  become: true
  become_user: "{{ netbox_postgresql_user }}"

- name: Ensure Redis is ready
  ansible.builtin.service:
    name: "{{ netbox_redis_service }}"
    state: started
