---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart NetBox
  ansible.builtin.service:
    name: netbox
    state: restarted
    enabled: true
  become: true
  when: netbox_setup_systemd | bool

- name: Restart NetBox rqworker
  ansible.builtin.service:
    name: netbox-rqworker
    state: restarted
    enabled: true
  become: true
  when: netbox_setup_systemd | bool

- name: Restart Apache2
  ansible.builtin.service:
    name: "{{ netbox_apache2_service }}"
    state: restarted
    enabled: true
  become: true
  when: netbox_setup_web_frontend | bool
